const meals = [
    { name: "Pizza", type: "dinner" },
    { name: "Toast with jam", type: "breakfast" },
    { name: "Fired eggs", type: "breakfast" },
    { name: "Spaghetti bolognese", type: "dinner" },
    { name: "Tuna sandwich", type: "lunch" },
    { name: "Roast chicken", type: "dinner" },
    { name: "Oatmeal", type: "breakfast" },
    { name: "Chicken salad", type: "lunch" },
    { name: "Steak with potatoes", type: "dinner" },
    { name: "Pancakes", type: "breakfast" },
    { name: "BLT sandwich", type: "lunch" },
    { name: "Fish and chips", type: "dinner" },
    { name: "Veggie wrap", type: "lunch" },
    { name: "Porridge", type: "breakfast" },
    { name: "Ham and cheese sandwich", type: "lunch" },
    { name: "Beef stir-fry", type: "dinner" },
    { name: "Yogurt with honey", type: "breakfast" },
    { name: "Grilled salmon", type: "dinner" },
    { name: "Caesar salad", type: "lunch" },
    { name: "French toast", type: "breakfast" },
    { name: "Vegetable curry", type: "dinner" },
    { name: "Egg salad sandwich", type: "lunch" },
    { name: "Cereal with milk", type: "breakfast" },
    { name: "Lasagna", type: "dinner" },
    { name: "Turkey wrap", type: "lunch" },
    { name: "Smoothie bowl", type: "breakfast" },
    { name: "Lamb chops", type: "dinner" },
    { name: "Quinoa salad", type: "lunch" },
    { name: "Bagel with cream cheese", type: "breakfast" },
    { name: "Chicken tikka masala", type: "dinner" },
    { name: "Pasta salad", type: "lunch" },
    { name: "Waffles", type: "breakfast" },
    { name: "Baked cod", type: "dinner" },
    { name: "Club sandwich", type: "lunch" },
    { name: "Omelette", type: "breakfast" },
    { name: "Stuffed peppers", type: "dinner" },
    { name: "Tofu stir-fry", type: "lunch" },
    { name: "Granola with fruit", type: "breakfast" },
    { name: "Roast beef", type: "dinner" },
    { name: "Falafel wrap", type: "lunch" },
    { name: "Avocado toast", type: "breakfast" },
    { name: "Shrimp pasta", type: "dinner" },
    { name: "Chicken Caesar wrap", type: "lunch" },
    { name: "Peanut butter and jelly sandwich", type: "breakfast" },
    { name: "Mushroom risotto", type: "dinner" },
    { name: "Sushi rolls", type: "lunch" },
    { name: "Greek yogurt parfait", type: "breakfast" },
    { name: "Pork chops", type: "dinner" },
    { name: "Caprese salad", type: "lunch" },
    { name: "Blueberry muffins", type: "breakfast" },
    { name: "Chicken fajitas", type: "dinner" },
    { name: "Tuna salad", type: "lunch" },
    { name: "Croissants", type: "breakfast" },
    { name: "Spicy tofu bowl", type: "dinner" },
    { name: "Chicken noodle soup", type: "lunch" },
    { name: "French omelette", type: "breakfast" },
    { name: "Beef tacos", type: "dinner" },
    { name: "Salmon sushi bowl", type: "lunch" },
    { name: "Chocolate chip pancakes", type: "breakfast" },
    { name: "Vegetable lasagna", type: "dinner" },
    { name: "Pita with hummus", type: "lunch" },
    { name: "Bacon and eggs", type: "breakfast" },
];

// Export meals as the default export
export default meals;

const mealTypes = ["breakfast", "lunch", "dinner"];

// Export mealTypes as a named export
export { mealTypes };
